package me.choco.generators.generators;

import me.choco.generators.generators.fuel.IFuelable;

/**
 * Represents a generator that can produce power for other generators
 * in the world. All power generators have an internal power buffer
 * 
 * @author Parker Hawke - 2008Choco
 */
public interface IPowerGenerator extends IFuelable {
	
	/**
	 * Get the amount of power generated by this generator per tick
	 * 
	 * @return the power generation per tick
	 */
	public float getPowerPerTick();
	
}